(ns kotoba.tatekata.process
  "process — the robot operation sequence per construction step.

  Ported from `kami-app-tatekata::process.rs` (kami-engine, Rust, retired per
  ADR-2607010000-kotoba-runtime-sdk-cljc-migration). Each construction step
  is a chain of robot operations (procure 調達 -> deliver 搬入 -> stage 搬送
  -> build 建方/据付/敷設/打設 -> fasten 締結/溶接 -> inspect 検査). The
  tatekata viewer plays these phases inside each step's window so the build
  is shown as an executable robotics procedure, not just a geometry reveal.

  This namespace is pure and takes ops data as a plain argument — it does
  NOT load anything itself (no I/O, per this repo's contract). The Rust
  original loaded a real `process.json`, generated by `process_gen.py` from
  `70-tools/e7m-sim/scenes/giemon-factory-r0/process.json` in the kami-engine
  monorepo; that upstream dataset is **not present** in this checkout (it was
  searched for broadly and confirmed absent, not merely unfound) and is not
  reproduced here. `resources/kotoba/tatekata/process-ops.edn` ships a small
  hand-authored SYNTHETIC ops fixture for test coverage only — it exercises
  the same shape (`procure -> deliver -> stage -> <build action> -> fasten
  -> inspect`) but is not derived from or a substitute for the real
  construction-process dataset.

  Data shapes:
  - Op: `{:op/step :op/seq :op/action :op/label :op/robot :op/from :op/to
    :op/dur-min :op/process}`.
  - PhaseOp: an Op placed on the step's normalized timeline `[f0, f1)`:
    `{:phase/op <Op> :phase/f0 <float> :phase/f1 <float>}`.
  - StepPlan: per-step playback plan —
    `{:plan/ops [<PhaseOp> ...] :plan/build-start <float> :plan/build-end
    <float>}` — `build-start`/`build-end` is the window during which
    geometry actually grows (i.e. the 据付/締結 ops — after 調達/搬入/搬送,
    before 検査).")

(defn is-build?
  "True for any action other than the logistics/inspection bookends."
  [action]
  (not (contains? #{"procure" "deliver" "stage" "inspect"} action)))

(defn is-logistics?
  "True while a logistics op (搬入/搬送) is active — drives the delivery
  cart in the (unported) viewer host adapter."
  [action]
  (contains? #{"deliver" "stage"} action))

(defn plans
  "Build a per-step plan for each id in `step-ids`, keyed in the SAME order.
  `ops` is a flat seq of Op maps (see ns docstring); ops for a step are
  sorted by `:op/seq` and their `:op/dur-min` (floored at 0.1) normalized
  into `[0, 1)` timeline fractions."
  [ops step-ids]
  (mapv
   (fn [sid]
     (let [step-ops (->> ops (filter #(= (:op/step %) sid)) (sort-by :op/seq))
           total (max 1e-3 (reduce + (map #(max 0.1 (:op/dur-min %)) step-ops)))
           [phase _acc bs be]
           (reduce
            (fn [[phase acc bs be] o]
              (let [f0 (/ acc total)
                    dur (max 0.1 (:op/dur-min o))
                    acc' (+ acc dur)
                    f1 (/ acc' total)
                    build? (is-build? (:op/action o))
                    bs' (if build? (min bs f0) bs)
                    be' (if build? (max be f1) be)]
                [(conj phase {:phase/op o :phase/f0 f0 :phase/f1 f1}) acc' bs' be']))
            [[] 0.0 1.0 0.0]
            step-ops)
           [bs be] (if (> bs be) [0.0 1.0] [bs be])]
       {:plan/ops phase :plan/build-start bs :plan/build-end be}))
   step-ids))

(defn op-at
  "The PhaseOp active at within-step fraction `p` (0..1), or the last op if
  `p` is past the end (or there is no op covering `p`)."
  [{:keys [:plan/ops]} p]
  (or (first (filter (fn [po] (and (>= p (:phase/f0 po)) (< p (:phase/f1 po)))) ops))
      (last ops)))

(defn build-progress
  "Geometry build progress (0..1) for within-step fraction `p`: zero until
  the build window opens, then ramps to 1 across it."
  [{:keys [:plan/build-start :plan/build-end]} p]
  (let [span (max 1e-3 (- build-end build-start))]
    (min 1.0 (max 0.0 (/ (- p build-start) span)))))

(defn logistics-at
  "The within-op progress (0..1) if a logistics op (搬入/搬送) is active at
  fraction `p`, else nil."
  [{:keys [:plan/ops]} p]
  (some (fn [po]
          (when (and (is-logistics? (:op/action (:phase/op po)))
                     (>= p (:phase/f0 po))
                     (< p (:phase/f1 po)))
            (let [span (max 1e-3 (- (:phase/f1 po) (:phase/f0 po)))]
              (min 1.0 (max 0.0 (/ (- p (:phase/f0 po)) span))))))
        ops))
